const BOOKMARK_DATA = [
{ "title": "TPPP Traffic", "url": "https://cp-ess-prod-ds.kb.af-south-1.aws.elastic-cloud.com:9243/s/support/app/dashboards#/view/0b0d6280-3bc7-11ec-8235-49182b192410?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now%2Fd,to:now%2Fd))" },
{ "title": "iBankAdmin", "url": "https://directadmin.int.capinet/ibankAdmin/" },
{ "title": "Freeze Calendar", "url": "https://confluence.capitecbank.co.za:8443/pages/viewpage.action?pageId=255175410" },
{ "title": "Slack", "url": "https://app.slack.com/client/TE96G4NU9/CKUMM51G9?selected_team_id=TE96G4NU9&skip_onboarding=1" },
{ "title": "Investec Shares", "url": "https://www.investecss.co.za/CAPITEC/account/logon" },
{ "title": "Risk Register", "url": "https://confluence.capitecbank.co.za:8443/display/IBUSSD/Risk+register" },
{ "title": "Monthly reports", "url": "https://capitecbank.atlassian.net/wiki/spaces/PTMR/pages/3369174463/Internet+Banking+and+USSD" },
{ "title": "Kibana", "url": "https://cp-ess-prod.kb.af-south-1.aws.elastic-cloud.com:9243/spaces/space_selector" },
{ "title": "USSD Confluence", "url": "https://confluence.capitecbank.co.za:8443/pages/viewpage.action?pageId=762708889" },
{ "title": "Udemy Business", "url": "https://capitec.udemy.com/organization/home/" },
{ "title": "BOARD", "url": "https://capitec-c1.board.com/" },
{ "title": "Success Factors", "url": "https://performancemanager.successfactors.eu/sf/start" },
{ "title": "ITSM", "url": "https://itsm.capitecbank.co.za/HEAT/Default.aspx" },
{ "title": "ESS", "url": "https://vipselfservice.capitecbank.co.za/webselfservice/#/signin" },
{ "title": "Google Search", "url": "http://google.com" },
{ "title": "Hacker News", "url": "https://news.ycombinator.com" },
{ "title": "iBank Admin", "url": "https://directadmin.int.capinet/ibankAdmin/" },
{ "title": "License to Innovate", "url": "https://confluence.capitecbank.co.za:8443/display/CVP/License+to+Innovate" },
{ "title": "Upcoming Birthdays", "url": "https://capitecbank.sharepoint.com/sites/C-Family/SitePages/BirthdayThisWeek.aspx" },
{ "title": "Client Value Confluence", "url": "https://confluence.capitecbank.co.za:8443/pages/viewpage.action?spaceKey=CVP&title=Client+Value+Product+Line" },
{ "title": "Project Health PowerBI", "url": "https://app.powerbi.com/groups/me/apps/67c1b2eb-053d-4557-abf2-38013638efe7/web-contents/f15145ce-50c3-b7c4-5628-7138093fe467?ctid=a428b46f-c29b-4a6c-85f1-8e05c10b6671&experience=power-bi" },
{ "title": "Easy Equities PowerBI", "url": "https://app.powerbi.com/groups/e3d42d1c-2d1b-4552-89fa-1579dbf92b4b/reports/5b1bf89c-d0c7-462b-9566-fe6712490289/ReportSection803e850aba9bbc3ed3f4?ctid=a428b46f-c29b-4a6c-85f1-8e05c10b6671&experience=power-bi" },
{ "title": "Fraud PowerBI", "url": "https://app.powerbi.com/groups/58ab73ad-c6e7-4104-a98d-ab28abd61c8b/reports/a3c1c4b5-e27f-4c6e-98e7-d8f478edce49/ReportSection35fb522706da34e00ca9?ctid=a428b46f-c29b-4a6c-85f1-8e05c10b6671&experience=power-bi" },
{ "title": "Instana", "url": "https://production-capitecbank.instana.io/#/applications;app.orderBy=callsAgg;app.orderDirection=DESC;app.page=7;app.pageSize=20;app.query;app.disabledColumns=!~;app.enabledColumns=!~?timeline.ws=300000&timeline.to&timeline.fm&timeline.ar=true" },
{ "title": "Risk Register (cloud)", "url" : "https://capitecbank.atlassian.net/jira/software/c/projects/IRR/boards/2060"},
{ "title": "Team confluence (cloud)", "url": "https://capitecbank.atlassian.net/wiki/spaces/IBUSSD/overview"}, 
{ "title": "IT Risk Dashboard", "url":"https://capitecbank.atlassian.net/jira/dashboards/10813"},
{ "title": "Enterprise Risk Dashboard", "url": "https://capitecbank.atlassian.net/jira/dashboards/11093" },
{ "title": "eVantage AWS Learning", "url":"https://evantage.gilmoreglobal.com/#/" },
{ "title": "PagerDuty", "url": "https://capitec-bank.pagerduty.com/incidents" },
{ "title": "Gitlab", "url":"https://git.int.capinet/" },
{ "title": "1password (Capitec)", "url": "https://capitec.1password.com/signin?landing-page=%2Fintegrations%2Fdirectory" },
{ "title": "Promofocus", "url":"https://pomofocus.io/" },
{ "title": "Instana", "url":"https://production-capitecbank.instana.io/#/websiteMonitoring/website;websiteId=BQOqyKTDTduAB8-9CJTkYQ/summary?timeline.ws=86400000&timeline.to&timeline.fm&timeline.ar=false"},
{ "title": "Cloud Masters", "url": "https://capitecbank.sharepoint.com/sites/CapitecCloudMasters/SitePages/Home.aspx" },
];
